### ISSUE TITLE
mpq: "too many open files" error

### ISSUE THREAD

**Issue by mewmew** [sanctuary/mpq#2]
It seems that `mpq` is too optimized :) We should impose a limit for open file descriptors based on `ulimit --file-descriptor-count`.

```
u@x1 ~/D/g/s/g/m/s/d1> time mpq
2019/03/17 15:02:00 open diabdat/ui_art/seldiff.pcx: too many open files
```

On my system, a total of 1024 file descriptors are allowed to be open by a given process.

```
u@x1 ~> ulimit --file-descriptor-count
1024
```

**Comment by alexindigo** [comment]
Same here

**Comment by mewmew** [comment]
Hi Alex!

@7i who wrote the `mpq` tool has now become a father :) Thus it could take some time before he gets a chance to code on this tool next time.

For now, it works for me to simply re-run the tool, and most often on the second try, it finishes without errors.

Cheers,
Robin

**Comment by alexindigo** [comment]
@mewmew Thanks for the details. I totally understand the father part :) Good luck to him.

As for the bug, I re-ran it 10+ times with the same issue (different files though).

**Comment by mewmew** [comment]
> As for the bug, I re-ran it 10+ times with the same issue (different files though).

Oh, that's rough.

I made an update to the tool that makes in run sequentially by default. Try to update to the latest version and run again.

```
go get -u github.com/sanctuary/mpq
```

Then just run the tool as you did before. (If you want to try running concurrently add the `-concurrent` flag.)

Oh, and please report back if it works or not :)

Cheers!

**Comment by alexindigo** [comment]
Yay! It worked as magic 🙏 
Thanks a lot.

**Comment by mewmew** [comment]
> Yay! It worked as magic :pray:

Yay! Happy to hear :)

Also, for future reference, using `-concurrent` may speed up the process a lot, so we may still want to find a sweet spot for having all those CPU cores running without running into the issue of having "too many open files".

# Sequential time

Average run time: 3.00 seconds.

```bash
$ time mpq -m /home/u/_share_/diabdat.mpq
real 3.16
user 2.40
sys 0.56

$ time mpq -m /home/u/_share_/diabdat.mpq
real 2.91
user 2.41
sys 0.48

$ time mpq -m /home/u/_share_/diabdat.mpq
real 2.93
user 2.31
sys 0.57
```

# Concurrent time

Average run time: 1.28 seconds.

```bash
$ time mpq -concurrent -m /home/u/_share_/diabdat.mpq
real 1.24
user 3.63
sys 0.64

$ time mpq -concurrent -m /home/u/_share_/diabdat.mpq
real 1.31
user 3.64
sys 0.67

$ time mpq -concurrent -m /home/u/_share_/diabdat.mpq
real 1.29
user 3.57
sys 0.72
```
